name: React CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test --if-present

      - name: Build Project
        run: npm run build

      - name: Upload hasil build
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download hasil build
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: out

      - name: Install Vercel CLI Terbaru
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Info
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy to Vercel
        # Memindahkan hasil build ke folder standar Vercel dan deploy
        run: |
          # 1. Buat struktur folder yang dibutuhkan Vercel Build Output API
          mkdir -p .vercel/output/static
          
          # 2. Pindahkan file statis hasil build Vite ke folder /static
          cp -r out/* .vercel/output/static/
          
          # 3. Buat file config.json agar Vercel tahu ini aplikasi Single Page App (SPA)
          echo '{"version": 3, "routes": [{"handle": "filesystem"}, {"src": "/.*", "dest": "/index.html"}]}' > .vercel/output/config.json
          
          # 4. Jalankan deploy
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}